// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsAgentClient is the client API for MetricsAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsAgentClient interface {
	PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error)
	UpdateMetric(ctx context.Context, in *UpdateMetricRequest, opts ...grpc.CallOption) (*UpdateMetricResponse, error)
	UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error)
	LoadMetric(ctx context.Context, in *LoadMetricRequest, opts ...grpc.CallOption) (*LoadMetricResponse, error)
}

type metricsAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsAgentClient(cc grpc.ClientConnInterface) MetricsAgentClient {
	return &metricsAgentClient{cc}
}

func (c *metricsAgentClient) PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error) {
	out := new(PingDBResponse)
	err := c.cc.Invoke(ctx, "/metricagent.MetricsAgent/PingDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsAgentClient) UpdateMetric(ctx context.Context, in *UpdateMetricRequest, opts ...grpc.CallOption) (*UpdateMetricResponse, error) {
	out := new(UpdateMetricResponse)
	err := c.cc.Invoke(ctx, "/metricagent.MetricsAgent/UpdateMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsAgentClient) UpdateMetrics(ctx context.Context, in *UpdateMetricsRequest, opts ...grpc.CallOption) (*UpdateMetricsResponse, error) {
	out := new(UpdateMetricsResponse)
	err := c.cc.Invoke(ctx, "/metricagent.MetricsAgent/UpdateMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsAgentClient) LoadMetric(ctx context.Context, in *LoadMetricRequest, opts ...grpc.CallOption) (*LoadMetricResponse, error) {
	out := new(LoadMetricResponse)
	err := c.cc.Invoke(ctx, "/metricagent.MetricsAgent/LoadMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsAgentServer is the server API for MetricsAgent service.
// All implementations must embed UnimplementedMetricsAgentServer
// for forward compatibility
type MetricsAgentServer interface {
	PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error)
	UpdateMetric(context.Context, *UpdateMetricRequest) (*UpdateMetricResponse, error)
	UpdateMetrics(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error)
	LoadMetric(context.Context, *LoadMetricRequest) (*LoadMetricResponse, error)
	mustEmbedUnimplementedMetricsAgentServer()
}

// UnimplementedMetricsAgentServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsAgentServer struct {
}

func (UnimplementedMetricsAgentServer) PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingDB not implemented")
}
func (UnimplementedMetricsAgentServer) UpdateMetric(context.Context, *UpdateMetricRequest) (*UpdateMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetric not implemented")
}
func (UnimplementedMetricsAgentServer) UpdateMetrics(context.Context, *UpdateMetricsRequest) (*UpdateMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetrics not implemented")
}
func (UnimplementedMetricsAgentServer) LoadMetric(context.Context, *LoadMetricRequest) (*LoadMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMetric not implemented")
}
func (UnimplementedMetricsAgentServer) mustEmbedUnimplementedMetricsAgentServer() {}

// UnsafeMetricsAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsAgentServer will
// result in compilation errors.
type UnsafeMetricsAgentServer interface {
	mustEmbedUnimplementedMetricsAgentServer()
}

func RegisterMetricsAgentServer(s grpc.ServiceRegistrar, srv MetricsAgentServer) {
	s.RegisterService(&MetricsAgent_ServiceDesc, srv)
}

func _MetricsAgent_PingDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAgentServer).PingDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricagent.MetricsAgent/PingDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAgentServer).PingDB(ctx, req.(*PingDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsAgent_UpdateMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAgentServer).UpdateMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricagent.MetricsAgent/UpdateMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAgentServer).UpdateMetric(ctx, req.(*UpdateMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsAgent_UpdateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAgentServer).UpdateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricagent.MetricsAgent/UpdateMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAgentServer).UpdateMetrics(ctx, req.(*UpdateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsAgent_LoadMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAgentServer).LoadMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricagent.MetricsAgent/LoadMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAgentServer).LoadMetric(ctx, req.(*LoadMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsAgent_ServiceDesc is the grpc.ServiceDesc for MetricsAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metricagent.MetricsAgent",
	HandlerType: (*MetricsAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingDB",
			Handler:    _MetricsAgent_PingDB_Handler,
		},
		{
			MethodName: "UpdateMetric",
			Handler:    _MetricsAgent_UpdateMetric_Handler,
		},
		{
			MethodName: "UpdateMetrics",
			Handler:    _MetricsAgent_UpdateMetrics_Handler,
		},
		{
			MethodName: "LoadMetric",
			Handler:    _MetricsAgent_LoadMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
